### ISSUE TITLE
shyaml keys show function dump representations 

### ISSUE THREAD

**Issue by groovehunter** [0k/shyaml#12]
I use the test.yaml from README in the example shyaml keys. The same happens with my custom yaml file (I cannot put that here). I use commit d35421826a0fb8dc8c02183beb65622fa29d883f
installed via python setup.py install

    cat test.yaml | shyaml keys
    <function dump at 0x7f526cac3938>
    <function dump at 0x7f526cac3938>
    <function dump at 0x7f526cac3938>
    <function dump at 0x7f526cac3938>
    <function dump at 0x7f526cac3938>

**Comment by vaab** [comment]
Oops, my bad. This reminds me that this project really need some sort of automated test system. However this is a major regression, so I'll first patch and release the fix.

Many thanks for your feedback.

Fixed and released ``shyaml`` ``0.3.3``, can you tell me if all is okay for you also ?
