### ISSUE TITLE
py2 or py3 errors on the following

### ISSUE THREAD

**Issue by yarko** [0k/shyaml#30]
Given the following  yaml file:

[foo.yml.txt](https://github.com/0k/shyaml/files/587121/foo.yml.txt)

and either python2.7 or python3.5, the examples on get, keys-0, etc. all seem to fail in various ways.

The example file loads fine in python yaml.

**Comment by szepeviktor** [comment]
You could get help much faster if you provide details and outputs.

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by vaab** [comment]
Sorry for the late answer.
The given file loads correctly with ``shyaml`` and various actions (like ``get-values``, ``keys``).
I'll close this report as invalid. Feel free to re-open it with additional data to reproduce your issue.
