### ISSUE TITLE
doesn't support multiple documents

### ISSUE THREAD

**Issue by chrishiestand** [0k/shyaml#32]
In the case of multiple documents in a yaml stream, it would be great to be able to use shyaml to parse and extract data via pipe.

**Comment by vaab** [comment]
There's a specification issue right now with implementing this feature, probably outlining some previous bad design decision, let me write this down to remember:
This basicly revolve around : What is the output expected to be ?
A natural answer might be: a standard output stream of entities. 

The following question is what will be the separator between the entities ? 
Here again it seems that the most natural answers could be either:
- YAML separator ``---`` to have an output that is still a YAML stream (which seems to make sense if you use the ``--yaml`` option) for further processing with ``shyaml`` or any other YAML tool,
- or maybe ``\n`` or ``NUL`` char if you don't use ``--yaml`` option and want to further process directly in bash.
- and both could be implemented and useable through options on the command line.

For now, no big issues.

Quite naturaly, we could also want that any current action (querying structures, sequences...) should be usable in a stream.
The specification problem arise when considering the current actions available and their own output type (YAML or not) and separators which already mixes YAML, "\n" and NUL separator.

Consider for instance ``key-values-0`` : it uses ``NUL`` char separator, but allows (with the use of ``--yaml``) that both key and values are in full YAML. And this is quite useful : bash can process the key and value in one go and safely thanks to the ``NUL`` separator, and further process the value of the key through YAML tools.
Now this is the hard question: if I use ``key-values-0`` with ``--yaml``, what separator would I expect in a stream to separate different sets of keys and values ? 

There are indeed a lot of possible answers, but none for me seems elegant enough right now. I feel I'm missing a better solution and I'm open to change some of the constraints.

**Comment by vaab** [comment]
Version ``0.6.0`` is released and supports YAML document streams natively. Although, as documented here and in the ``README.rst``, only simple queries (``get-length``,``get-size``, ``get-value``) are supported.
