### ISSUE TITLE
Highly unlikely UnicodeEncodeError

### ISSUE THREAD

**Issue by szepeviktor** [0k/shyaml#35]
locale en_US.UTF-8
/usr/bin/env python ->Python 2.7.9
python-yaml 3.11-2
shyaml/master

```yaml
non-ascii: Zoltán
```

```bash
#!/bin/bash

echo "$(shyaml get-value non-ascii < s.yml)"

shyaml get-value non-ascii < s.yml
```

### Output

```
Traceback (most recent call last):
  File "/usr/local/bin/shyaml", line 429, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/shyaml", line 394, in main
    print(dump(value), end='')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 4: ordinal not in range(128)

Zoltán
```

Please advise.

**Comment by szepeviktor** [comment]
A rude but correct answer: http://stackoverflow.com/a/9942822

**Comment by szepeviktor** [comment]
Why only in a **subshell** ???

**Comment by vaab** [comment]
Hi, sorry for the late answer and thanks for your interest.
This is a well-know issue with python 2.7 : on subshells, ``sys.stdout.encoding`` is not set.
It can be set however through PYTHONIOENCODING shell variable. 
My suggestion would be to check that ``sys.stdout.encoding`` is set, and if not, use ``locale.getpreferredencoding()``.
What do you think of that ?

**Comment by vaab** [comment]
It is happening only in a subshell because python checks if it is talking to a ``tty`` or not. You can override this check by setting PYTHONIOENCODING:
cf https://github.com/python/cpython/blob/2.7/Python/pythonrun.c#L360

**Comment by szepeviktor** [comment]
Thank you!

I recommend to use shyaml **always** as `PYTHONIOENCODING="utf_8" shyaml ...`

**Comment by szepeviktor** [comment]
> My suggestion would be to check that sys.stdout.encoding is set, and if not, use locale.getpreferredencoding().
> What do you think of that ?

I've just tested it, it works!
