### ISSUE TITLE
installation on user space on cluster

### ISSUE THREAD

**Issue by achiappo** [0k/shyaml#39]
Hi, I successfully managed to install shymal on my personal machine using `pip`. However, I need it when running jobs on a batch farm to which I have access. From my user space on the cluster, I issued `$ pip install --user shyaml`, as I usually do to install pip packages there. The installation ended successfully, however it did not generate the executable in the bin folder (even because I don't have a local/bin/ folder). The installation only generated a `shyaml-0.5.0.dist-info/` folder in `.local/lib/python2.7/site-packages`. Is there a way to have it running in my circumstance? Thank you very much

**Comment by szepeviktor** [comment]
Try looking in `~/.local/bin`

**Comment by achiappo** [comment]
you're right! (how could I not think about it before?...). Thank you very much
