### ISSUE TITLE
Missing args do not raise informative error.

### ISSUE THREAD

**Issue by jeremy-donson** [0k/shyaml#41]
Aha, so I was not told of my error where I provided insufficient args?
Two args are required?

$ cat file | shyaml -y get-value <VALUE_NAME>

**All I wanted was a way to validate the yaml file, ONLY.**

As per bash, return code of 0 would be GOOD.
As per bash, return code of 1 would be BAD.  :)

Let's see if we can work together a bit?
- jeremy

NOTE:  My original email to you documented this issue in a gist...
https://gist.github.com/jeremy-donson/204b27e59f111f63b95830df7797789b

**Comment by vaab** [comment]
Hmm, sorry, left this a little long. I guess you are refering to this issue:

Calling:
```
shyaml -y
```

will raise an exception where it should give you an informative error.
This is due to the implementation of ``-y`` and the very simple and poor implementation of command line arguments. It is quite easy to fix.

**Comment by vaab** [comment]
Thanks for your interest and spotting this bug.
