### ISSUE TITLE
Homebrew formula is outdated (v0.5.2 vs 0.6.1)

### ISSUE THREAD

**Issue by werediver** [0k/shyaml#52]
It's a nice tool and it's convenient to install it via Homebrew, but currently the Homebrew [formula is pretty outdated](https://github.com/Homebrew/homebrew-core/blob/master/Formula/shyaml.rb) and installs v0.5.2, when the latest tagged version in this repository is v0.6.1.

Could somebody please update the formula? 🙏

**Comment by vaab** [comment]
Sorry for not having answered this in time. According to:
https://formulae.brew.sh/formula/shyaml
Is correctly set on 0.6.1 now. I'll close this if you don't mind.
